setup: Don't try to install if we couldn't add the apt-repo
Sometimes the repo might be down; in this case we might install an older
version than we wanted, and it's annoying to remember to uninstall the old version
before simply re-running the script.

diff --git a/.config/dhleong/setup b/.config/dhleong/setup
--- a/.config/dhleong/setup
+++ b/.config/dhleong/setup
@@ -58,6 +58,11 @@ ensure_brew_apt() {
         echo "Installing: $cli_name..."
         if [ $apt_repo != '' ]; then
             sudo add-apt-repository -y $apt_repo
+
+            if [ $? -ne 0 ]; then
+                echo " -> Failed to add repo '$apt_repo', skipping $cli_name"
+                return 1
+            fi
         fi
         sudo apt-get install -y $apt_name
     else
